title: Getting started with Hasura
tagline: Getting started with Hasura
description: Getting started with Hasura

template:
  name: getting-started-with-hasura
  repo: getting-started-with-hasura

# before:
# - type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Docker Compose
  description: Docker compose getting started
#   event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#   actions: # a list of the actions that will occur when the step is triggered by an event
#   - type: # the type of action, full list at https://lab.github.com/docs/actions

- title: Env file
  description: Env file

- title: First table
  description: First table

- title: Permissions
  description: permissions

- title: Migrations
  description: advanced migrations

- title: Advanced permissions
  description: advanced permissions
